### PR TITLE
core: align all icons with figma export

### PR DESCRIPTION
**Pull request by SutuSebastian**
### Changes

- fix structure
- fix naming convention (files and folders)
- add `width` and `height` attributes (`24px`)
- removed duplicated and deprecated icons
- add recently added icons (missing)
- remove inline hex colors, replace with `currentColor`

### CODE REVIEW

**Comment by sparecycles** [comment]
outline/map-location <-> solid/map-pin-alt

**Comment by SutuSebastian** [comment]
> * outline/map-location <-> solid/map-pin-alt
> * "papper-plane" and "newspapper" (paper!)
> * "circle check" (one of the few with a space in the name)
> * solid/face-laughz <-> outline/face-laugh

Fixed

**Comment by zoltanszogyenyi** [comment]
Awesome job on the PR! Quick question though - what file name changes are there as I believe this will again impact the @shinokada's Svelte version of icons.

By the way, Shinichi - we messed up with these typos and icon names, we've talked internally with @robert1508 and @SutuSebastian so that we will be extra careful with the file names and differences.

The official source will continue to be this repository, even though we'll try to keep perfect parity between the Figma file and our website too.

**Comment by SutuSebastian** [comment]
> Awesome job on the PR! Quick question though - what file name changes are there as I believe this will again impact the @shinokada's Svelte version of icons.
> 
> By the way, Shinichi - we messed up with these typos and icon names, we've talked internally with @robert1508 and @SutuSebastian so that we will be extra careful with the file names and differences.
> 
> The official source will continue to be this repository, even though we'll try to keep perfect parity between the Figma file and our website too.

I'll fill up the PR description with all changes when its all nice and tidy 🙌

**Comment by shinokada** [comment]
@zoltanszogyenyi Is it possible to make me to access Setting for https://github.com/themesberg/flowbite-svelte-icons?
Or can you update the URL under About to https://flowbite-svelte-icons.vercel.app/ ?

image

**Comment by shinokada** [comment]
Regarding Flowbite-Svelte-Icons, I use the file names for the component names. So please do not use the same file names in different sub directories. Also please do not use (, [ etc for the file names.
Thank you for updating the icons.

**Comment by zoltanszogyenyi** [comment]
Hey @shinokada,

I've given you higher permissions. Can you now access the settings area?

Cheers,
Zoltan

**Review by zoltanszogyenyi — APPROVED** [review]
Looks good to me. Awesome job on the PR. We have to be super careful from now on so that the Figma is equal to this repo as this is the repo for the source of truth. Otherwise, we can go ahead and merge and then propagate to our website and React and Svelte.

@shinokada there may be file name changes here, hopefully the last ones since this is our main sync - is there a way you can do an update so the Svelte users don't have to go through another major breaking change? Like keep the legacy imports working.

**Review by robert1508 — APPROVED** [review]

**Comment by shinokada** [comment]
@zoltanszogyenyi Thank you for the access permission. I will update Flowbite-Svelte-Icons once this is merged.

**Pull request merged**
